version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/images:/var/www/images
    depends_on:
      - webapp
      - eventsapp
      - senderapp
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always 
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 
  mongodb:
    container_name: mongoddb
    image: mongo:latest
    restart: always 
    volumes:
      - './data/mongodb:/data/db'   
  webapp: 
    container_name: webapp
    image: registry.gitlab.com/rapidcodelab/gopusher/web-app 
    restart: always 
    environment: 
      LICENSE_KEY: #your license key
      LOGIN: demo  # select your login  
      PASSWORD: demo   # select your password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    volumes:
      - './data/images:/images'    
    depends_on:
      - mongodb  
    links:
      - mongodb    
  eventsapp: 
    container_name: eventsapp
    image: registry.gitlab.com/rapidcodelab/gopusher/events-app  
    restart: always 
    environment: 
      LICENSE_KEY: #your license key
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    links:
      - mongodb
  senderapp:
    container_name: senderapp
    image: registry.gitlab.com/rapidcodelab/gopusher/sender-app 
    restart: always  
    environment:
      WORKERS_AMMOUNT: 500    
      LICENSE_KEY: #your license key
      VAPID_PUBLIC_KEY: cvsdfj34985209384209834 # Enter your VAPID Public Key
      VAPID_PRIVATE_KEY: jf30uf2908tr827f3874fu  # Enter your VAPID Private Key
      SUBJECT_MAIL:  mailto:login@domain.com # Enter your VAPID Subject mail
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      WEB_HOST: https://web.rapidcodelab.com/images/ #change to your webapp domain
    depends_on:
      - mongodb
    links:
      - mongodb 
  # ##  Uncomment if you want to use publisjer api 
  # apiapp: 
  #   container_name: apiapp
  #   image: registry.gitlab.com/rapidcodelab/gopusher/api-app 
  #   environment:
  #     MONGO_HOST: mongodb
  #     MONGO_PORT: 27017 
  #   depends_on:
  #     - mongodb  
  #   links:
  #     - mongodb  